function [out] = Cbn(x,u,p)

%% *******************************************************%
%% function [out] = Cbn(x,u,p)                            %
%%                                                        %
%% This is a temporary file. Do NOT edit THIS file!!      %
%% Generated by <Cexpr2Matlab.m>, Version 3.0             %
%%                                                        %
%% Ch. Eck, Measurement and Control Lab., ETH Zurich      %
%% *******************************************************%

global OMEGA REARTH eEARTH
Omega=OMEGA;

Cbnnum = zeros(3,3);

t1=x(2.0);
t2=cos(t1);
t3=x(3.0);
t4=cos(t3);
t6=x(1.0);
t7=cos(t6);
t8=sin(t3);
t10=sin(t6);
t11=sin(t1);
t12=t10*t11;
t16=t7*t11;
Cbnnum(1,1)=t2*t4;
Cbnnum(1,2)=-t7*t8+t12*t4;
Cbnnum(1,3)=t10*t8+t16*t4;
Cbnnum(2,1)=t2*t8;
Cbnnum(2,2)=t7*t4+t12*t8;
Cbnnum(2,3)=-t10*t4+t16*t8;
Cbnnum(3,1)=-t11;
Cbnnum(3,2)=t10*t2;
Cbnnum(3,3)=t7*t2;

out = Cbnnum;
