function [out] = Tw(x,u,p)

%% *******************************************************%
%% function [out] = Tw(x,u,p)                             %
%%                                                        %
%% This is a temporary file. Do NOT edit THIS file!!      %
%% Generated by <Cexpr2Matlab.m>, Version 3.0             %
%%                                                        %
%% Ch. Eck, Measurement and Control Lab., ETH Zurich      %
%% *******************************************************%

global OMEGA REARTH eEARTH
Omega=OMEGA;

Twnum = zeros(3,3);

t1=x(1.0);
t2=sin(t1);
t3=x(2.0);
t4=sin(t3);
t7=1/cos(t3);
t9=cos(t1);
Twnum(1,1)=1.0;
Twnum(1,2)=t2*t4*t7;
Twnum(1,3)=t9*t4*t7;
Twnum(2,2)=t9;
Twnum(2,3)=-t2;
Twnum(3,2)=t7*t2;
Twnum(3,3)=t9*t7;

out = Twnum;
